"""
Creative Generation Tasks

Test ability to:
- Produce novel outputs
- Combine concepts in creative ways
- Generate coherent structures
- Balance novelty with quality
"""

import random
import math
from typing import List, Dict, Any, Tuple, Set
from dataclasses import dataclass
from collections import defaultdict


@dataclass
class GeneratedArtifact:
    """Something generated by an agent."""
    content: Any
    novelty_score: float = 0.0
    quality_score: float = 0.0
    coherence_score: float = 0.0


class CreativeGenerationTask:
    """
    Base class for creative generation tasks.

    Evaluates on:
    - Novelty: how different from previous outputs
    - Quality: how well-formed/functional
    - Coherence: internal consistency
    """

    def __init__(self, difficulty: float = 0.5):
        self.difficulty = difficulty
        self.archive: List[GeneratedArtifact] = []

    def compute_novelty(self, artifact: GeneratedArtifact) -> float:
        """
        Compute novelty relative to archive.

        Higher score = more different from existing artifacts.
        """
        if not self.archive:
            return 1.0

        # Compare to archive
        similarities = []
        for existing in self.archive:
            similarity = self._similarity(artifact.content, existing.content)
            similarities.append(similarity)

        # Novelty is inverse of max similarity
        max_similarity = max(similarities)
        return 1.0 - max_similarity

    def _similarity(self, content1: Any, content2: Any) -> float:
        """Compute similarity between two artifacts (0-1)."""
        # Override in subclasses
        if content1 == content2:
            return 1.0
        return 0.0

    def evaluate_generation(
        self,
        generator: Any,
        num_generations: int = 20
    ) -> Dict[str, float]:
        """
        Evaluate creative generation.

        Returns metrics on novelty, quality, coherence.
        """
        artifacts = []

        for _ in range(num_generations):
            try:
                # Generate artifact
                content = self._call_generator(generator)

                artifact = GeneratedArtifact(content=content)

                # Evaluate
                artifact.novelty_score = self.compute_novelty(artifact)
                artifact.quality_score = self.compute_quality(artifact)
                artifact.coherence_score = self.compute_coherence(artifact)

                artifacts.append(artifact)
                self.archive.append(artifact)

            except:
                pass

        if not artifacts:
            return {
                'avg_novelty': 0.0,
                'avg_quality': 0.0,
                'avg_coherence': 0.0,
                'creative_score': 0.0
            }

        avg_novelty = sum(a.novelty_score for a in artifacts) / len(artifacts)
        avg_quality = sum(a.quality_score for a in artifacts) / len(artifacts)
        avg_coherence = sum(a.coherence_score for a in artifacts) / len(artifacts)

        # Creative score balances novelty and quality
        creative_score = (avg_novelty * avg_quality * avg_coherence) ** (1/3)

        return {
            'avg_novelty': avg_novelty,
            'avg_quality': avg_quality,
            'avg_coherence': avg_coherence,
            'creative_score': creative_score,
            'num_generated': len(artifacts)
        }

    def _call_generator(self, generator: Any) -> Any:
        """Call generator to produce content."""
        if callable(generator):
            return generator()
        return generator

    def compute_quality(self, artifact: GeneratedArtifact) -> float:
        """Compute quality score (override in subclass)."""
        return 0.5

    def compute_coherence(self, artifact: GeneratedArtifact) -> float:
        """Compute coherence score (override in subclass)."""
        return 0.5


class NovelPatternTask(CreativeGenerationTask):
    """
    Generate novel patterns/sequences.

    Test: Create sequences that are both novel and have structure.
    """

    def __init__(self, difficulty: float = 0.5, pattern_length: int = 10):
        super().__init__(difficulty)
        self.pattern_length = pattern_length

    def _similarity(self, pattern1: List, pattern2: List) -> float:
        """Compute pattern similarity."""
        if len(pattern1) != len(pattern2):
            # Normalize lengths
            min_len = min(len(pattern1), len(pattern2))
            pattern1 = pattern1[:min_len]
            pattern2 = pattern2[:min_len]

        if not pattern1:
            return 0.0

        # Hamming distance for discrete patterns
        matches = sum(1 for a, b in zip(pattern1, pattern2) if a == b)
        return matches / len(pattern1)

    def compute_quality(self, artifact: GeneratedArtifact) -> float:
        """
        Quality = how well-structured the pattern is.

        Checks for:
        - Appropriate length
        - Variety in elements
        - Some regularity (not pure random)
        """
        pattern = artifact.content

        if not isinstance(pattern, (list, tuple)):
            return 0.0

        # Check length
        length_score = 1.0 if len(pattern) == self.pattern_length else 0.5

        # Check variety
        if len(pattern) == 0:
            return 0.0

        unique = len(set(pattern))
        variety_score = min(1.0, unique / max(1, len(pattern) / 2))

        # Check regularity (some autocorrelation)
        regularity_score = self._compute_autocorrelation(pattern)

        return (length_score + variety_score + regularity_score) / 3

    def _compute_autocorrelation(self, pattern: List) -> float:
        """Compute autocorrelation (measure of regularity)."""
        if len(pattern) < 4:
            return 0.5

        # Check for repeating subsequences
        for period in range(2, len(pattern) // 2 + 1):
            matches = 0
            comparisons = 0
            for i in range(len(pattern) - period):
                if pattern[i] == pattern[i + period]:
                    matches += 1
                comparisons += 1

            if comparisons > 0:
                correlation = matches / comparisons
                if correlation > 0.3:
                    return min(1.0, correlation)

        return 0.5

    def compute_coherence(self, artifact: GeneratedArtifact) -> float:
        """
        Coherence = internal consistency.

        For patterns: transitions follow some logic.
        """
        pattern = artifact.content

        if not isinstance(pattern, (list, tuple)) or len(pattern) < 2:
            return 0.0

        # Check transition consistency
        transitions = defaultdict(set)
        for i in range(len(pattern) - 1):
            from_elem = pattern[i]
            to_elem = pattern[i + 1]
            transitions[from_elem].add(to_elem)

        # Coherence: elements have consistent transitions
        # (not every element transitions to everything)
        if not transitions:
            return 0.0

        avg_transitions = sum(len(targets) for targets in transitions.values()) / len(transitions)
        max_transitions = len(set(pattern))

        coherence = 1.0 - (avg_transitions / max(max_transitions, 1))
        return max(0.0, min(1.0, coherence))


class ConceptCombinationTask(CreativeGenerationTask):
    """
    Combine concepts in novel ways.

    Example: Given "bird" and "machine", generate "airplane"

    Tests conceptual blending.
    """

    def __init__(self, difficulty: float = 0.5):
        super().__init__(difficulty)
        self.concept_space = self._build_concept_space()

    def _build_concept_space(self) -> Dict[str, Dict[str, Any]]:
        """Build space of concepts with features."""
        concepts = {
            'bird': {
                'features': {'flies', 'wings', 'feathers', 'organic', 'lightweight'},
                'category': 'animal'
            },
            'machine': {
                'features': {'mechanical', 'metal', 'powered', 'manufactured'},
                'category': 'artifact'
            },
            'fish': {
                'features': {'swims', 'fins', 'scales', 'organic', 'aquatic'},
                'category': 'animal'
            },
            'vehicle': {
                'features': {'transport', 'mechanical', 'powered', 'wheels_or_wings'},
                'category': 'artifact'
            },
            'plant': {
                'features': {'roots', 'photosynthesis', 'organic', 'stationary'},
                'category': 'organism'
            },
            'house': {
                'features': {'shelter', 'walls', 'roof', 'stationary'},
                'category': 'structure'
            },
            'computer': {
                'features': {'electronic', 'computation', 'data_processing', 'manufactured'},
                'category': 'technology'
            },
            'human': {
                'features': {'intelligent', 'bipedal', 'organic', 'social'},
                'category': 'animal'
            }
        }
        return concepts

    def generate_combination_task(self) -> Tuple[str, str]:
        """Generate a concept combination task."""
        concepts = list(self.concept_space.keys())
        concept1 = random.choice(concepts)
        concept2 = random.choice([c for c in concepts if c != concept1])
        return concept1, concept2

    def _similarity(self, combo1: Dict, combo2: Dict) -> float:
        """Similarity between concept combinations."""
        if not isinstance(combo1, dict) or not isinstance(combo2, dict):
            return 0.0

        # Compare features
        features1 = combo1.get('features', set())
        features2 = combo2.get('features', set())

        if not features1 or not features2:
            return 0.0

        intersection = features1 & features2
        union = features1 | features2

        return len(intersection) / len(union) if union else 0.0

    def compute_quality(self, artifact: GeneratedArtifact) -> float:
        """
        Quality of concept combination.

        Should:
        - Include features from both source concepts
        - Add emergent features
        - Be coherent
        """
        combination = artifact.content

        if not isinstance(combination, dict):
            return 0.0

        # Artifact should specify source concepts and resulting features
        source1 = combination.get('source1')
        source2 = combination.get('source2')
        features = combination.get('features', set())

        if not source1 or not source2 or not features:
            return 0.0

        # Get source features
        features1 = self.concept_space.get(source1, {}).get('features', set())
        features2 = self.concept_space.get(source2, {}).get('features', set())

        # Quality: includes features from both + novel features
        from_source1 = features & features1
        from_source2 = features & features2
        novel = features - (features1 | features2)

        # Score
        coverage_score = min(1.0, (len(from_source1) + len(from_source2)) / 4)
        novelty_score = min(1.0, len(novel) / 2)

        return (coverage_score + novelty_score) / 2

    def compute_coherence(self, artifact: GeneratedArtifact) -> float:
        """
        Coherence: features don't contradict.

        Example: can't be both "organic" and "manufactured"
        """
        combination = artifact.content

        if not isinstance(combination, dict):
            return 0.0

        features = combination.get('features', set())

        # Check for contradictions
        contradictions = [
            ('organic', 'manufactured'),
            ('stationary', 'mobile'),
            ('aquatic', 'aerial'),
            ('living', 'non_living')
        ]

        for feat1, feat2 in contradictions:
            if feat1 in features and feat2 in features:
                return 0.0

        return 1.0


class StructureGenerationTask(CreativeGenerationTask):
    """
    Generate coherent structures (graphs, trees, etc).

    Test: Create structures that are both novel and well-formed.
    """

    def __init__(self, difficulty: float = 0.5):
        super().__init__(difficulty)
        self.structure_type = 'graph'

    def _similarity(self, struct1: Dict, struct2: Dict) -> float:
        """Graph similarity."""
        if not isinstance(struct1, dict) or not isinstance(struct2, dict):
            return 0.0

        nodes1 = set(struct1.get('nodes', []))
        nodes2 = set(struct2.get('nodes', []))

        edges1 = set(map(tuple, struct1.get('edges', [])))
        edges2 = set(map(tuple, struct2.get('edges', [])))

        # Jaccard similarity
        node_sim = len(nodes1 & nodes2) / len(nodes1 | nodes2) if (nodes1 | nodes2) else 0.0
        edge_sim = len(edges1 & edges2) / len(edges1 | edges2) if (edges1 | edges2) else 0.0

        return (node_sim + edge_sim) / 2

    def compute_quality(self, artifact: GeneratedArtifact) -> float:
        """
        Quality of generated structure.

        - Appropriate size
        - Not too sparse/dense
        - Connected
        """
        struct = artifact.content

        if not isinstance(struct, dict):
            return 0.0

        nodes = struct.get('nodes', [])
        edges = struct.get('edges', [])

        if not nodes:
            return 0.0

        n = len(nodes)

        # Size score (prefer moderate size)
        size_score = min(1.0, n / 10) if n < 10 else max(0.0, 1.0 - (n - 10) / 20)

        # Density score (not too sparse, not complete)
        num_edges = len(edges)
        max_edges = n * (n - 1) // 2
        density = num_edges / max_edges if max_edges > 0 else 0

        density_score = 1.0 - abs(density - 0.3)  # Prefer ~30% density

        # Connectivity score
        connectivity_score = 1.0 if self._is_connected(struct) else 0.5

        return (size_score + density_score + connectivity_score) / 3

    def _is_connected(self, struct: Dict) -> bool:
        """Check if graph is connected."""
        nodes = struct.get('nodes', [])
        edges = struct.get('edges', [])

        if not nodes:
            return True

        # Build adjacency
        adj = defaultdict(set)
        for edge in edges:
            if len(edge) >= 2:
                u, v = edge[0], edge[1]
                adj[u].add(v)
                adj[v].add(u)

        # BFS from first node
        visited = set()
        queue = [nodes[0]]
        visited.add(nodes[0])

        while queue:
            node = queue.pop(0)
            for neighbor in adj[node]:
                if neighbor not in visited:
                    visited.add(neighbor)
                    queue.append(neighbor)

        return len(visited) == len(nodes)

    def compute_coherence(self, artifact: GeneratedArtifact) -> float:
        """
        Coherence: structure is well-formed.

        - All edges reference existing nodes
        - No duplicate edges
        """
        struct = artifact.content

        if not isinstance(struct, dict):
            return 0.0

        nodes = set(struct.get('nodes', []))
        edges = struct.get('edges', [])

        if not nodes:
            return 0.0

        # Check all edges reference real nodes
        valid_edges = 0
        for edge in edges:
            if len(edge) >= 2:
                if edge[0] in nodes and edge[1] in nodes:
                    valid_edges += 1

        if not edges:
            return 1.0

        validity_score = valid_edges / len(edges)

        # Check for duplicates
        unique_edges = len(set(map(tuple, edges)))
        uniqueness_score = unique_edges / len(edges) if edges else 1.0

        return (validity_score + uniqueness_score) / 2
